package ajdi.request;

import com.sun.jdi.request.MethodEntryRequest;

import adb.ShadowMaster;
import ajdi.AdviceApplication;
import ajdi.JoinPoint;
import ajdi.ObjectReference;
import ajdi.ThreadReference;

public interface AdviceApplicationRequest extends EventRequest{


	  /**
   * Restricts the events generated by this request to those in
   * the given thread.
   * @param thread the thread to filter on.
   * @throws InvalidRequestStateException if this request is currently
   * enabled or has been deleted. 
   * Filters may be added only to disabled requests.
   */
  void addThreadFilter(ThreadReference thread);


  /**
   * Restricts the events generated by this request to those in
   * which the currently executing instance ("this") is the object
   * specified.
   * <P>
   * Not all targets support this operation. 
   * Use {@link VirtualMachine#canUseInstanceFilters()}
   * to determine if the operation is supported.
   * @since 1.4
   * @param instance the object which must be the current instance
   * in order to pass this filter.
   * @throws java.lang.UnsupportedOperationException if 
   * the target virtual machine does not support this 
   * operation.
   * @throws InvalidRequestStateException if this request is currently
   * enabled or has been deleted. 
   * Filters may be added only to disabled requests.
   */
  void addInstanceFilter(ObjectReference instance);
  
  AdviceApplication adviceApplication();

}
