/*
 * generated by Xtext
 */
package xtext.comprendo;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ComprendoRuntimeModule extends xtext.comprendo.AbstractComprendoRuntimeModule {

}
