/*
 * generated by Xtext
 */
package xtext.comprendo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ComprendoUiModule extends xtext.comprendo.ui.AbstractComprendoUiModule {
	public ComprendoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
