/*
* generated by Xtext
*/
package xtext.cool.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import xtext.cool.services.CoolGrammarAccess;

public class CoolParser extends AbstractContentAssistParser {
	
	@Inject
	private CoolGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected xtext.cool.ui.contentassist.antlr.internal.InternalCoolParser createParser() {
		xtext.cool.ui.contentassist.antlr.internal.InternalCoolParser result = new xtext.cool.ui.contentassist.antlr.internal.InternalCoolParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getBooleanValAccess().getAlternatives(), "rule__BooleanVal__Alternatives");
					put(grammarAccess.getCoordinatorDeclarationAccess().getGroup(), "rule__CoordinatorDeclaration__Group__0");
					put(grammarAccess.getCoordinatorBodyAccess().getGroup(), "rule__CoordinatorBody__Group__0");
					put(grammarAccess.getCoordinatorBodyAccess().getGroup_2(), "rule__CoordinatorBody__Group_2__0");
					put(grammarAccess.getCoordinatorBodyAccess().getGroup_2_2(), "rule__CoordinatorBody__Group_2_2__0");
					put(grammarAccess.getCoordinatorBodyAccess().getGroup_3(), "rule__CoordinatorBody__Group_3__0");
					put(grammarAccess.getCoordinatorBodyAccess().getGroup_3_2(), "rule__CoordinatorBody__Group_3_2__0");
					put(grammarAccess.getCoordinatorBodyAccess().getGroup_4(), "rule__CoordinatorBody__Group_4__0");
					put(grammarAccess.getCoordinatorBodyAccess().getGroup_4_2(), "rule__CoordinatorBody__Group_4_2__0");
					put(grammarAccess.getCondVarAccess().getGroup(), "rule__CondVar__Group__0");
					put(grammarAccess.getOrdVarAccess().getGroup(), "rule__OrdVar__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getCoordinatorDeclarationAccess().getGranularityAssignment_0(), "rule__CoordinatorDeclaration__GranularityAssignment_0");
					put(grammarAccess.getCoordinatorDeclarationAccess().getClassNameAssignment_2(), "rule__CoordinatorDeclaration__ClassNameAssignment_2");
					put(grammarAccess.getCoordinatorDeclarationAccess().getBodyAssignment_3(), "rule__CoordinatorDeclaration__BodyAssignment_3");
					put(grammarAccess.getCoordinatorBodyAccess().getCondVarsAssignment_2_1(), "rule__CoordinatorBody__CondVarsAssignment_2_1");
					put(grammarAccess.getCoordinatorBodyAccess().getCondVarsAssignment_2_2_1(), "rule__CoordinatorBody__CondVarsAssignment_2_2_1");
					put(grammarAccess.getCoordinatorBodyAccess().getOrdVarsAssignment_3_1(), "rule__CoordinatorBody__OrdVarsAssignment_3_1");
					put(grammarAccess.getCoordinatorBodyAccess().getOrdVarsAssignment_3_2_1(), "rule__CoordinatorBody__OrdVarsAssignment_3_2_1");
					put(grammarAccess.getCoordinatorBodyAccess().getSelfexMethodsAssignment_4_1(), "rule__CoordinatorBody__SelfexMethodsAssignment_4_1");
					put(grammarAccess.getCoordinatorBodyAccess().getSelfexMethodsAssignment_4_2_1(), "rule__CoordinatorBody__SelfexMethodsAssignment_4_2_1");
					put(grammarAccess.getCondVarAccess().getNameAssignment_0(), "rule__CondVar__NameAssignment_0");
					put(grammarAccess.getCondVarAccess().getValueAssignment_2(), "rule__CondVar__ValueAssignment_2");
					put(grammarAccess.getOrdVarAccess().getNameAssignment_0(), "rule__OrdVar__NameAssignment_0");
					put(grammarAccess.getOrdVarAccess().getValueAssignment_2(), "rule__OrdVar__ValueAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			xtext.cool.ui.contentassist.antlr.internal.InternalCoolParser typedParser = (xtext.cool.ui.contentassist.antlr.internal.InternalCoolParser) parser;
			typedParser.entryRuleCoordinatorDeclaration();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public CoolGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CoolGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
