/* Generated By:JJTree: Do not edit this line. ASTAndExpr.java */

package cool.frontend.ast;

public class ASTAndExpr extends SimpleNode {
  public ASTAndExpr(int id) {
    super(id);
  }

  public ASTAndExpr(COOLParser p, int id) {
    super(p, id);
  }

}
