/* Generated By:JJTree: Do not edit this line. ASTBreakStmnt.java */

package cool.frontend.ast;

public class ASTBreakStmnt extends SimpleNode {
  public ASTBreakStmnt(int id) {
    super(id);
  }

  public ASTBreakStmnt(COOLParser p, int id) {
    super(p, id);
  }

}
