/* Generated By:JJTree: Do not edit this line. ASTBracketExpr.java */

package cool.frontend.ast;

public class ASTBracketExpr extends SimpleNode {
  public ASTBracketExpr(int id) {
    super(id);
  }

  public ASTBracketExpr(COOLParser p, int id) {
    super(p, id);
  }

}
