/* Generated By:JJTree: Do not edit this line. ASTCoordinatorDecl.java */

package cool.frontend.ast;

public class ASTCoordinatorDecl extends SimpleNode {
  public ASTCoordinatorDecl(int id) {
    super(id);
  }

  public ASTCoordinatorDecl(COOLParser p, int id) {
    super(p, id);
  }

}
