/* Generated By:JJTree: Do not edit this line. ASTEmptyStmnt.java */

package cool.frontend.ast;

public class ASTEmptyStmnt extends SimpleNode {
  public ASTEmptyStmnt(int id) {
    super(id);
  }

  public ASTEmptyStmnt(COOLParser p, int id) {
    super(p, id);
  }

}
