/* Generated By:JJTree: Do not edit this line. ASTImportDecl.java */

package cool.frontend.ast;

public class ASTImportDecl extends SimpleNode {
  public ASTImportDecl(int id) {
    super(id);
  }

  public ASTImportDecl(COOLParser p, int id) {
    super(p, id);
  }

}
