/* Generated By:JJTree: Do not edit this line. ASTRelExpr.java */

package cool.frontend.ast;

public class ASTRelExpr extends SimpleNode {
  public ASTRelExpr(int id) {
    super(id);
  }

  public ASTRelExpr(COOLParser p, int id) {
    super(p, id);
  }

}
