/* Generated By:JJTree: Do not edit this line. ASTReqAndExpr.java */

package cool.frontend.ast;

public class ASTReqAndExpr extends SimpleNode {
  public ASTReqAndExpr(int id) {
    super(id);
  }

  public ASTReqAndExpr(COOLParser p, int id) {
    super(p, id);
  }

}
