/* Generated By:JJTree: Do not edit this line. ASTReqNegExpr.java */

package cool.frontend.ast;

public class ASTReqNegExpr extends SimpleNode {
  public ASTReqNegExpr(int id) {
    super(id);
  }

  public ASTReqNegExpr(COOLParser p, int id) {
    super(p, id);
  }

}
