/* Generated By:JJTree: Do not edit this line. ASTType.java */

package cool.frontend.ast;

public class ASTType extends SimpleNode {
  public ASTType(int id) {
    super(id);
  }

  public ASTType(COOLParser p, int id) {
    super(p, id);
  }

}
