/* Generated By:JJTree: Do not edit this line. ASTVarRef.java */

package cool.frontend.ast;

public class ASTVarRef extends SimpleNode {
  public ASTVarRef(int id) {
    super(id);
  }

  public ASTVarRef(COOLParser p, int id) {
    super(p, id);
  }

}
