/* Generated By:JJTree: Do not edit this line. ASTAssignExpr.java */

package cool.frontend.ast;

public class ASTAssignExpr extends SimpleNode {
  public ASTAssignExpr(int id) {
    super(id);
  }

  public ASTAssignExpr(COOLParser p, int id) {
    super(p, id);
  }

}
