/* Generated By:JJTree: Do not edit this line. ASTContinueStmnt.java */

package cool.frontend.ast;

public class ASTContinueStmnt extends SimpleNode {
  public ASTContinueStmnt(int id) {
    super(id);
  }

  public ASTContinueStmnt(COOLParser p, int id) {
    super(p, id);
  }

}
