/* Generated By:JJTree: Do not edit this line. ASTMultExpr.java */

package cool.frontend.ast;

public class ASTMultExpr extends SimpleNode {
  public ASTMultExpr(int id) {
    super(id);
  }

  public ASTMultExpr(COOLParser p, int id) {
    super(p, id);
  }

}
