/* Generated By:JJTree: Do not edit this line. ASTNewArrExpr.java */

package cool.frontend.ast;

public class ASTNewArrExpr extends SimpleNode {
  public ASTNewArrExpr(int id) {
    super(id);
  }

  public ASTNewArrExpr(COOLParser p, int id) {
    super(p, id);
  }

}
