/* Generated By:JJTree: Do not edit this line. ASTExclOrExpr.java */

package cool.frontend.ast;

public class ASTExclOrExpr extends SimpleNode {
  public ASTExclOrExpr(int id) {
    super(id);
  }

  public ASTExclOrExpr(COOLParser p, int id) {
    super(p, id);
  }

}
