/* Generated By:JJTree: Do not edit this line. ASTIfStmnt.java */

package cool.frontend.ast;

public class ASTIfStmnt extends SimpleNode {
  public ASTIfStmnt(int id) {
    super(id);
  }

  public ASTIfStmnt(COOLParser p, int id) {
    super(p, id);
  }

}
