/* Generated By:JJTree: Do not edit this line. ASTLabeledStmnt.java */

package cool.frontend.ast;

public class ASTLabeledStmnt extends SimpleNode {
  public ASTLabeledStmnt(int id) {
    super(id);
  }

  public ASTLabeledStmnt(COOLParser p, int id) {
    super(p, id);
  }

}
