/* Generated By:JJTree: Do not edit this line. ASTMethodName.java */

package cool.frontend.ast;

public class ASTMethodName extends SimpleNode {
  public ASTMethodName(int id) {
    super(id);
  }

  public ASTMethodName(COOLParser p, int id) {
    super(p, id);
  }

}
