/*
* generated by Xtext
*/
package xtext.cool.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.cool.services.CoolGrammarAccess;

public class CoolParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CoolGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected xtext.cool.parser.antlr.internal.InternalCoolParser createParser(XtextTokenStream stream) {
		return new xtext.cool.parser.antlr.internal.InternalCoolParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CoordinatorDeclaration";
	}
	
	public CoolGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CoolGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
