/* Generated By:JJTree: Do not edit this line. ASTCondOrExpr.java */

package cool.frontend.ast;

public class ASTCondOrExpr extends SimpleNode {
  public ASTCondOrExpr(int id) {
    super(id);
  }

  public ASTCondOrExpr(COOLParser p, int id) {
    super(p, id);
  }

}
