/* Generated By:JJTree: Do not edit this line. ASTClassName.java */

package cool.frontend.ast;

public class ASTClassName extends SimpleNode {
  public ASTClassName(int id) {
    super(id);
  }

  public ASTClassName(COOLParser p, int id) {
    super(p, id);
  }

}
