/* Generated By:JJTree: Do not edit this line. ASTDoStmnt.java */

package cool.frontend.ast;

public class ASTDoStmnt extends SimpleNode {
  public ASTDoStmnt(int id) {
    super(id);
  }

  public ASTDoStmnt(COOLParser p, int id) {
    super(p, id);
  }

}
