/* Generated By:JJTree: Do not edit this line. ASTFieldDecl.java */

package cool.frontend.ast;

public class ASTFieldDecl extends SimpleNode {
  public ASTFieldDecl(int id) {
    super(id);
  }

  public ASTFieldDecl(COOLParser p, int id) {
    super(p, id);
  }

}
