/* Generated By:JJTree: Do not edit this line. ASTInitArr.java */

package cool.frontend.ast;

public class ASTInitArr extends SimpleNode {
  public ASTInitArr(int id) {
    super(id);
  }

  public ASTInitArr(COOLParser p, int id) {
    super(p, id);
  }

}
