/* Generated By:JJTree: Do not edit this line. ASTReqVarRef.java */

package cool.frontend.ast;

public class ASTReqVarRef extends SimpleNode {
  public ASTReqVarRef(int id) {
    super(id);
  }

  public ASTReqVarRef(COOLParser p, int id) {
    super(p, id);
  }

}
