/* Generated By:JJTree: Do not edit this line. ASTShiftExpr.java */

package cool.frontend.ast;

public class ASTShiftExpr extends SimpleNode {
  public ASTShiftExpr(int id) {
    super(id);
  }

  public ASTShiftExpr(COOLParser p, int id) {
    super(p, id);
  }

}
