/* Generated By:JJTree: Do not edit this line. ASTVarInit.java */

package cool.frontend.ast;

public class ASTVarInit extends SimpleNode {
  public ASTVarInit(int id) {
    super(id);
  }

  public ASTVarInit(COOLParser p, int id) {
    super(p, id);
  }

}
