/* Generated By:JJTree: Do not edit this line. ASTAddExpr.java */

package cool.frontend.ast;

public class ASTAddExpr extends SimpleNode {
  public ASTAddExpr(int id) {
    super(id);
  }

  public ASTAddExpr(COOLParser p, int id) {
    super(p, id);
  }

}
