/* Generated By:JJTree: Do not edit this line. ASTGranularity.java */

package cool.frontend.ast;

public class ASTGranularity extends SimpleNode {
  public ASTGranularity(int id) {
    super(id);
  }

  public ASTGranularity(COOLParser p, int id) {
    super(p, id);
  }

}
