/* Generated By:JJTree: Do not edit this line. ASTOnExit.java */

package cool.frontend.ast;

public class ASTOnExit extends SimpleNode {
  public ASTOnExit(int id) {
    super(id);
  }

  public ASTOnExit(COOLParser p, int id) {
    super(p, id);
  }

}
