/* Generated By:JJTree: Do not edit this line. ASTReqBracketExpr.java */

package cool.frontend.ast;

public class ASTReqBracketExpr extends SimpleNode {
  public ASTReqBracketExpr(int id) {
    super(id);
  }

  public ASTReqBracketExpr(COOLParser p, int id) {
    super(p, id);
  }

}
