/* Generated By:JJTree: Do not edit this line. ASTReqOrExpr.java */

package cool.frontend.ast;

public class ASTReqOrExpr extends SimpleNode {
  public ASTReqOrExpr(int id) {
    super(id);
  }

  public ASTReqOrExpr(COOLParser p, int id) {
    super(p, id);
  }

}
