/* Generated By:JJTree: Do not edit this line. ASTRequires.java */

package cool.frontend.ast;

public class ASTRequires extends SimpleNode {
  public ASTRequires(int id) {
    super(id);
  }

  public ASTRequires(COOLParser p, int id) {
    super(p, id);
  }

}
