/* Generated By:JJTree: Do not edit this line. ASTSwitchStmnt.java */

package cool.frontend.ast;

public class ASTSwitchStmnt extends SimpleNode {
  public ASTSwitchStmnt(int id) {
    super(id);
  }

  public ASTSwitchStmnt(COOLParser p, int id) {
    super(p, id);
  }

}
