/* Generated By:JJTree: Do not edit this line. ASTUnaryExpr.java */

package cool.frontend.ast;

public class ASTUnaryExpr extends SimpleNode {
  public ASTUnaryExpr(int id) {
    super(id);
  }

  public ASTUnaryExpr(COOLParser p, int id) {
    super(p, id);
  }

}
