package cool.frontend.ast;

/* Generated By:JJTree&JavaCC: Do not edit this line. COOLParserConstants.java */
public interface COOLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int COORDINATOR = 9;
  int MUTEX = 10;
  int SELFEX = 11;
  int ONENTRY = 12;
  int ONEXIT = 13;
  int CONDITION = 14;
  int IF = 15;
  int DO = 16;
  int ELSE = 17;
  int BREAK = 18;
  int CONTINUE = 19;
  int TRUE = 20;
  int FALSE = 21;
  int PER = 22;
  int CLASS = 23;
  int OBJECT = 24;
  int FINAL = 25;
  int NEW = 26;
  int BOOLEAN = 27;
  int BYTE = 28;
  int CHAR = 29;
  int SHORT = 30;
  int INT = 31;
  int FLOAT = 32;
  int LONG = 33;
  int DOUBLE = 34;
  int REQUIRES = 35;
  int WHILE = 36;
  int FOR = 37;
  int CASE = 38;
  int SWITCH = 39;
  int DEFAULTKW = 40;
  int PACKAGE = 41;
  int IMPORT = 42;
  int ALPHA = 43;
  int DIGIT = 44;
  int FLOATNUM = 45;
  int NUMBER = 46;
  int NAME = 47;
  int STRING = 48;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"coordinator\"",
    "\"mutex\"",
    "\"selfex\"",
    "\"on_entry\"",
    "\"on_exit\"",
    "\"condition\"",
    "\"if\"",
    "\"do\"",
    "\"else\"",
    "\"break\"",
    "\"continue\"",
    "\"true\"",
    "\"false\"",
    "\"per\"",
    "\"class\"",
    "\"object\"",
    "\"final\"",
    "\"new\"",
    "\"boolean\"",
    "\"byte\"",
    "\"char\"",
    "\"short\"",
    "\"int\"",
    "\"float\"",
    "\"long\"",
    "\"double\"",
    "\"requires\"",
    "\"while\"",
    "\"for\"",
    "\"case\"",
    "\"switch\"",
    "\"default\"",
    "\"package\"",
    "\"import\"",
    "<ALPHA>",
    "<DIGIT>",
    "<FLOATNUM>",
    "<NUMBER>",
    "<NAME>",
    "<STRING>",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\".\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"-\"",
    "\"~\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"!=\"",
    "\"==\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"++\"",
    "\"--\"",
    "\":\"",
  };

}
