/* Generated By:JJTree: Do not edit this line. ast\COOLParserTreeConstants.java */

package cool.frontend.ast;

public interface COOLParserTreeConstants
{
  public int JJTCOORDINATORDECL = 0;
  public int JJTGRANULARITY = 1;
  public int JJTCOORDINATIONSPEC = 2;
  public int JJTFIELDDECL = 3;
  public int JJTCONDFIELDDECL = 4;
  public int JJTSELFEXDECL = 5;
  public int JJTMUTEXDECL = 6;
  public int JJTVOID = 7;
  public int JJTVARINIT = 8;
  public int JJTINITARR = 9;
  public int JJTMETHODNAME = 10;
  public int JJTMETHODMANAGERDECL = 11;
  public int JJTREQUIRES = 12;
  public int JJTONENTRY = 13;
  public int JJTONEXIT = 14;
  public int JJTREQOREXPR = 15;
  public int JJTREQANDEXPR = 16;
  public int JJTREQEQEXPR = 17;
  public int JJTREQNEGEXPR = 18;
  public int JJTREQBRACKETEXPR = 19;
  public int JJTREQVARREF = 20;
  public int JJTATOM = 21;
  public int JJTTYPE = 22;
  public int JJTCONDOREXPR = 23;
  public int JJTCONDANDEXPR = 24;
  public int JJTINCLOREXPR = 25;
  public int JJTEXCLOREXPR = 26;
  public int JJTANDEXPR = 27;
  public int JJTEQEXPR = 28;
  public int JJTRELEXPR = 29;
  public int JJTSHIFTEXPR = 30;
  public int JJTADDEXPR = 31;
  public int JJTMULTEXPR = 32;
  public int JJTASSIGNEXPR = 33;
  public int JJTUNARYEXPR = 34;
  public int JJTBRACKETEXPR = 35;
  public int JJTVARREF = 36;
  public int JJTNEWARREXPR = 37;
  public int JJTBLOCKSTMNT = 38;
  public int JJTIFSTMNT = 39;
  public int JJTWHILESTMNT = 40;
  public int JJTFORSTMNT = 41;
  public int JJTFORINIT = 42;
  public int JJTDOSTMNT = 43;
  public int JJTBREAKSTMNT = 44;
  public int JJTCONTINUESTMNT = 45;
  public int JJTSWITCHSTMNT = 46;
  public int JJTCASEBLOCK = 47;
  public int JJTLABELEDSTMNT = 48;
  public int JJTEMPTYSTMNT = 49;
  public int JJTCLASSNAME = 50;
  public int JJTPACKAGEDECL = 51;
  public int JJTIMPORTDECL = 52;


  public String[] jjtNodeName = {
    "CoordinatorDecl",
    "Granularity",
    "CoordinationSpec",
    "FieldDecl",
    "CondFieldDecl",
    "SelfexDecl",
    "MutexDecl",
    "void",
    "VarInit",
    "InitArr",
    "MethodName",
    "MethodManagerDecl",
    "Requires",
    "OnEntry",
    "OnExit",
    "ReqOrExpr",
    "ReqAndExpr",
    "ReqEqExpr",
    "ReqNegExpr",
    "ReqBracketExpr",
    "ReqVarRef",
    "Atom",
    "Type",
    "CondOrExpr",
    "CondAndExpr",
    "InclOrExpr",
    "ExclOrExpr",
    "AndExpr",
    "EqExpr",
    "RelExpr",
    "ShiftExpr",
    "AddExpr",
    "MultExpr",
    "AssignExpr",
    "UnaryExpr",
    "BracketExpr",
    "VarRef",
    "NewArrExpr",
    "BlockStmnt",
    "IfStmnt",
    "WhileStmnt",
    "ForStmnt",
    "ForInit",
    "DoStmnt",
    "BreakStmnt",
    "ContinueStmnt",
    "SwitchStmnt",
    "CaseBlock",
    "LabeledStmnt",
    "EmptyStmnt",
    "ClassName",
    "PackageDecl",
    "ImportDecl",
  };
}
