/*
* generated by Xtext
*/
package xtext.cool.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class CoolOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
