/*
 * generated by Xtext
 */
package xtext.cool.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CoolUiModule extends xtext.cool.ui.AbstractCoolUiModule {
	public CoolUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
