/* Generated By:JJTree: Do not edit this line. ASTCoordinationSpec.java */

package cool.frontend.ast;

public class ASTCoordinationSpec extends SimpleNode {
  public ASTCoordinationSpec(int id) {
    super(id);
  }

  public ASTCoordinationSpec(COOLParser p, int id) {
    super(p, id);
  }

}
