/* Generated By:JJTree: Do not edit this line. ASTCaseBlock.java */

package cool.frontend.ast;

public class ASTCaseBlock extends SimpleNode {
  public ASTCaseBlock(int id) {
    super(id);
  }

  public ASTCaseBlock(COOLParser p, int id) {
    super(p, id);
  }

}
