/* Generated By:JJTree: Do not edit this line. ASTForInit.java */

package cool.frontend.ast;

public class ASTForInit extends SimpleNode {
  public ASTForInit(int id) {
    super(id);
  }

  public ASTForInit(COOLParser p, int id) {
    super(p, id);
  }

}
