/* Generated By:JJTree: Do not edit this line. ASTInclOrExpr.java */

package cool.frontend.ast;

public class ASTInclOrExpr extends SimpleNode {
  public ASTInclOrExpr(int id) {
    super(id);
  }

  public ASTInclOrExpr(COOLParser p, int id) {
    super(p, id);
  }

}
