/* Generated By:JJTree: Do not edit this line. ASTMutexDecl.java */

package cool.frontend.ast;

public class ASTMutexDecl extends SimpleNode {
  public ASTMutexDecl(int id) {
    super(id);
  }

  public ASTMutexDecl(COOLParser p, int id) {
    super(p, id);
  }

}
