/* Generated By:JJTree: Do not edit this line. ASTMethodManagerDecl.java */

package cool.frontend.ast;

public class ASTMethodManagerDecl extends SimpleNode {
  public ASTMethodManagerDecl(int id) {
    super(id);
  }

  public ASTMethodManagerDecl(COOLParser p, int id) {
    super(p, id);
  }

}
