/* Generated By:JJTree: Do not edit this line. ASTReqEqExpr.java */

package cool.frontend.ast;

public class ASTReqEqExpr extends SimpleNode {
  public ASTReqEqExpr(int id) {
    super(id);
  }

  public ASTReqEqExpr(COOLParser p, int id) {
    super(p, id);
  }

}
