/* Generated By:JJTree: Do not edit this line. ASTSelfexDecl.java */

package cool.frontend.ast;

public class ASTSelfexDecl extends SimpleNode {
  public ASTSelfexDecl(int id) {
    super(id);
  }

  public ASTSelfexDecl(COOLParser p, int id) {
    super(p, id);
  }

}
