/* Generated By:JJTree: Do not edit this line. ASTWhileStmnt.java */

package cool.frontend.ast;

public class ASTWhileStmnt extends SimpleNode {
  public ASTWhileStmnt(int id) {
    super(id);
  }

  public ASTWhileStmnt(COOLParser p, int id) {
    super(p, id);
  }

}
