/*
* generated by Xtext
*/
package xtext.cool;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CoolUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return xtext.cool.ui.internal.CoolActivator.getInstance().getInjector("xtext.cool.Cool");
	}
	
}
