/*
* generated by Xtext
*/
package xtext.cool.ui.contentassist;

import xtext.cool.ui.contentassist.AbstractCoolProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CoolProposalProvider extends AbstractCoolProposalProvider {

}
