/*
 * generated by Xtext
 */
package xtext.cool;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CoolRuntimeModule extends xtext.cool.AbstractCoolRuntimeModule {

}
