
/*
 * generated by Xtext
 */
 
package xtext.comprendo.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class ComprendoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return xtext.comprendo.ui.internal.ComprendoActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return xtext.comprendo.ui.internal.ComprendoActivator.getInstance().getInjector("xtext.comprendo.Comprendo");
	}
	
}
