/*
* generated by Xtext
*/
package xtext.comprendo.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ComprendoTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
